### ISSUE TITLE
[ActionBar] add action bar fixed

### ISSUE THREAD

**Issue by guillaumechervetaxa** [AxaGuilDEv/react-toolkit#182] opened 2019-04-26 12:51 UTC
![image](https://user-images.githubusercontent.com/43414465/56808830-ba9cc300-6832-11e9-9355-8ac493429a94.png)

**Comment by arnaudforaison** [comment] 2020-10-11 08:02
Duplicate of #146

**Closed** 2020-10-11 08:03 UTC
