### ISSUE TITLE
[Bug][Test] Snapshot failed for contribute, on Help.spec when clone the master

### ISSUE THREAD

**Issue by sisko59** [AxaGuilDEv/react-toolkit#675] opened 2020-09-01 14:02 UTC
### Issue and Steps to Reproduce

check out the master.
execute the command npm run test

#### Versions
1.3.16

#### Screenshots
![image](https://user-images.githubusercontent.com/11503659/91860727-5252c280-ec6c-11ea-9cfe-0b2b7dcfc07e.png)
![image](https://user-images.githubusercontent.com/11503659/91860744-554db300-ec6c-11ea-9ae2-9977b136ca4b.png)

#### Expected
Tests execute successfully

#### Actual

Test failed on Help.spec

**Comment by arnaudforaison** [comment] 2020-09-03 09:19
A migration PR #645 is in progress and doesn't seems to have this issue.

**Comment by sisko59** [comment] 2020-09-10 07:41
check these PR:
https://github.com/AxaGuilDEv/react-toolkit/pull/668
https://github.com/AxaGuilDEv/react-toolkit/pull/673
https://github.com/AxaGuilDEv/react-toolkit/pull/677

I think your version of master is anterior of the issue.

**Comment by arnaudforaison** [comment] 2020-10-09 15:19
Duplicate of #670

**Comment by xballoy** [comment] 2020-10-21 08:32
Should be fixed as we do not have dependencies with local path anymore as we flatten / remove "sub-projects" in #731 and #728.

**Closed by xballoy** 2020-10-21 08:32 UTC
Labels: bug
