### ISSUE TITLE
Number form component can't accept minus sign

### ISSUE THREAD

**Issue by johnmeunier** [AxaGuilDEv/react-toolkit#710] opened 2020-10-13 12:50 UTC
Native number accept minus sign, there is not reason that the toolkit component can't accept these values. 

It's possible for the moment if you use viewValue instead of value.

**Comment by johnmeunier** [comment] 2020-10-13 12:59
The input has a type text instead of number. Any idea why ? cc @guillaumechervet @guillaumechervetaxa  @guillaume-chervet

**Comment by xballoy** [comment] 2020-10-13 20:46
Duplicate of #365

@johnmeunier I already analysed the current package and I think we should rebuild it from scratch. From what I remember we do some weird things with the value / viewValue by converting a text to a number to a text (that's why we cannot type a minus sign or a coma / point).

**Comment by johnmeunier** [comment] 2020-10-14 06:30
Totally agree. But i don't know if there is a reason why the component is based on an input text.

**Comment by arnaudforaison** [comment] 2020-10-14 06:36
What do you think of using input text with pattern ?

**Comment by johnmeunier** [comment] 2020-10-14 06:37
I don't understand why. I think, to avoid such weird behavior like this one, it will be better to use what HTML natively proposes. In our case, for a number component we can use the input type number. And you ?

**Comment by xballoy** [comment] 2020-10-14 06:46
100% agree with John, why trying to mimic the input number with a type when there's already an input number available (an working on all our supported browsers).

**Comment by arnaudforaison** [comment] 2020-10-14 07:08
Totally agree to use native propose but how would you manage minus (it's seems to be a feature) ?

**Comment by johnmeunier** [comment] 2020-10-14 07:08
Minus is natively supported in a number input.

**Comment by arnaudforaison** [comment] 2020-10-14 07:10
Sorry I think I wasn't.

**Closed** 2021-02-18 11:02 UTC
Labels: Component: Form, Type: Bug, good first issue
